### ISSUE TITLE
TYPO3 8.7 compatibility

### ISSUE THREAD

**Issue by SvenJuergens** [pschriner/dm_develogerlog#2]
hi,

do you plan a release for TYPO3 8.7.x ?

**Comment by pschriner** [comment]
Hi,

I plan to release ASAP - but due to my kitchen having burned a couple of weeks ago I'm currently not able to do so in a timely manner (priorities...).

I'll try to release something in the next 10 days.

**Comment by SvenJuergens** [comment]
(⊙_☉) omg, I hope you and your family are doing well.
so take your time, real life have always Prio one

**Comment by pschriner** [comment]
Hi, should be working with 8.7 now.

**Comment by SvenJuergens** [comment]
many thanks for your work :)
