### ISSUE TITLE
Release 0.7.2

### ISSUE THREAD

**Issue by 7elix** [pschriner/dm_develogerlog#6]
Dear Patrick,

please tag a 0.7.2 release on github.com and packagist.org to be in sync with composer.typo3.org (TER).

https://packagist.org/packages/diemedialen/dm-developerlog
https://composer.typo3.org/satis.html#!/dm-developerlog

**Comment by pschriner** [comment]
Done.

I should probable embrace a travis script that builds from tags ;D

**Comment by 7elix** [comment]
:) or web-hook. THANKS!
